# Authorization roles mapped from the Keycloak realm_access.roles JWT claim
authz.admin-role = dashboard-admin
authz.user-role = dashboard-user

#User management properties
user-mgmt.token-endpoint = /realms/${keycloak.realm}/protocol/openid-connect/token
user-mgmt.user-role = dashboard-user
user-mgmt.default-roles = dashboard-user
user-mgmt.user-attributes = telephone,position,affiliation
user-mgmt.group-attributes = long_name
